# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        name:        '%env(PROJECT_NAME)%$'
        handler_id:  Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler

    http_client:
        default_options:
            verify_peer: false
            verify_host: false
            timeout: 15
            headers:
                'User-Agent': 'VKAndroidApp/6.54-9332 (Android 11; SDK 30; armeabi-v7a; samsung SM-G970F; ru; 2280x1080)'

    #esi: true
    #fragments: true
    php_errors:
        log: true
