hwi_oauth:
    # list of names of the firewalls in which this bundle is active, this setting MUST be set
    firewall_names: [main]

    # https://github.com/hwi/HWIOAuthBundle/blob/master/Resources/doc/2-configuring_resource_owners.md
    resource_owners:
        vkontakte:
            type:                vkontakte
            client_id:           '8078221'
            client_secret:       '9WBo7Jq5p7ainKGPbEfz'
            scope: 'friends,offline'

    http_client:
        default_options:
            verify_peer: false
            verify_host: false
            proxy: 'http://7R7Jcj:VF4XoT@198.20.160.75:8000'
            timeout: 15
            headers:
                'User-Agent': 'VKAndroidApp/6.54-9332 (Android 11; SDK 30; armeabi-v7a; samsung SM-G970F; ru; 2280x1080)'
