version: "3"

services:
    db:
        image: mariadb:10.3.34-focal
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - "db_app:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - "3306:3306"
        networks:
            - symfony
    php:
        build:
            context: ./php
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - symfony_docker_app_sync:/var/www/symfony/
        networks:
            - symfony
    nginx:
        build:
            context: ./nginx
        volumes:
            - symfony_docker_app_sync:/var/www/symfony/
        ports:
            - "80:80"
        networks:
            - symfony
        env_file:
            - .env.nginx

volumes:
    symfony_docker_app_sync:
        external: true
    db_app:

networks:
    symfony:
